// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AudioStream = { channels: bigint, codec_name: string | null, duration: number | null, sample_rate: bigint | null, };

export type Config = { copyright: string, lufs: LufsConfig, transcript_cmd: string, transcript_lang: Array<LangConfig>, };

export type FFmpegProgress = { title: string, fps: number, bitrate: string, total_size: bigint, elapsed_sec: number, elapsed_pct: bigint, speed: number, progress: string, };

export type LangConfig = { name: string, code: string, };

export type LowerThird = { path: string, duration: number, position: Array<string>, };

export type LufsConfig = { i: number, lra: number, tp: number, };

export type MediaFormat = { duration: number | null, nb_streams: bigint, size: bigint, };

export type MediaProbe = { format: MediaFormat, audio: Array<AudioStream>, video: Array<VideoStream>, };

export type Preset = { name: string, title: string, tooltip: string, filter_video: JsonValue, filter_audio: JsonValue, video: JsonValue, audio: JsonValue, container_video: string, container_audio: string, output_path: string, finished: bool, };

export type Task = { path: string, in: number, out: number, fade: boolean, lufs: boolean, transcript: string | null, probe: MediaProbe, presets: Array<Preset>, template: Template | null, target: string, active: bool, finished: bool, };

export type Template = { intro: string, intro_duration: number, outro: string, outro_duration: number, lower_thirds: Array<LowerThird>, };

export type VideoStream = { codec_name: string | null, aspect_ratio: string | null, nb_frames: bigint | null, duration: number | null, bit_rate: bigint | null, width: bigint | null, height: bigint | null, };
